apiVersion: v1
kind: Service
metadata:
  name: smollm-135m-instruct
  namespace: default
spec:
  ports:
  - name: http-smollm-135m-instruct
    port: 80
    protocol: TCP
    targetPort: 8000
  # The label selector should match the deployment labels & it is useful for prefix caching feature
  selector:
    app: smollm-135m-instruct
  sessionAffinity: None
  type: ClusterIP